use std::fmt::Debug;

use purple_garden_ir::{constant::Const, ptype::Type};

use crate::{AllocType, vm::Vm};

/// Raw VM word.
///
/// `Value` is the VM-internal scalar encoding. Its `From` impls are intentionally
/// limited to context-free values; embedding/syscall boundaries should use
/// [`FromVm`] and [`IntoVm`] instead.
#[derive(PartialEq, Clone, Default, Copy, Debug)]
#[repr(transparent)]
pub struct Value(pub u64);

impl Value {
    pub const UNDEF: Self = Self(0);

    #[inline(always)]
    #[must_use]
    pub fn as_int(&self) -> i64 {
        self.0 as i64
    }

    #[inline(always)]
    #[must_use]
    pub fn as_bool(&self) -> bool {
        self.0 != 0
    }

    #[inline(always)]
    #[must_use]
    pub fn as_f64(&self) -> f64 {
        f64::from_bits(self.0)
    }

    #[inline(always)]
    #[must_use]
    pub fn as_str<'t>(&self) -> &'t str {
        let ptr = self.as_ptr::<u8>();
        let len_size = std::mem::size_of::<usize>();
        let len = unsafe { *(ptr as *const usize) };
        let bytes = unsafe { std::slice::from_raw_parts(ptr.add(len_size), len) };
        unsafe { std::str::from_utf8_unchecked(bytes) }
    }

    #[inline(always)]
    #[must_use]
    pub fn as_ptr<T>(&self) -> *mut T {
        self.0 as *mut T
    }

    #[inline(always)]
    pub fn from_ptr<T>(ptr: *mut T) -> Self {
        Self(ptr as u64)
    }

    #[inline(always)]
    #[must_use]
    pub fn int_to_bool(&self) -> Self {
        Value::from(self.0 != 0)
    }

    #[inline(always)]
    #[must_use]
    pub fn int_to_f64(&self) -> Self {
        Value::from(self.as_int() as f64)
    }

    #[inline(always)]
    #[must_use]
    pub fn f64_to_int(&self) -> Self {
        Value::from(self.as_f64() as i64)
    }
}

impl<'c> From<Const<'c>> for Value {
    fn from(value: Const<'c>) -> Self {
        Self(match value {
            Const::False => 0u64,
            Const::True => 1u64,
            Const::Int(i) => i as u64,
            Const::Double(bits) => bits,
            _ => unimplemented!("0xDEADAFFE"),
        })
    }
}

impl From<bool> for Value {
    fn from(value: bool) -> Self {
        Self(u64::from(value))
    }
}

impl From<i64> for Value {
    fn from(value: i64) -> Self {
        Self(value as u64)
    }
}

impl From<usize> for Value {
    fn from(value: usize) -> Self {
        Self(value as u64)
    }
}

impl From<f64> for Value {
    fn from(value: f64) -> Self {
        Self(value.to_bits())
    }
}

pub trait PgType {
    const TYPE: Type<'static>;
}

/// Decode a Rust value from a raw VM [`Value`].
///
/// Implemented for primitives and generated by `GardenValue`/`GardenOpaque`.
/// Package authors normally use those derives instead of implementing this
/// trait directly.
pub trait FromVm<'vm>: Sized {
    fn from_vm(vm: &'vm Vm, value: Value) -> Self;
}

/// Encode a Rust return value into a raw VM value.
///
/// The VM is available for return types that need runtime allocation, such as
/// strings. The caller still decides where the returned [`Value`] is written.
/// Package authors normally use `GardenValue`/`GardenOpaque` instead of
/// implementing this trait directly.
pub trait IntoVm {
    fn into_vm(self, vm: &mut Vm) -> Value;
}

#[doc(hidden)]
pub fn alloc_record(vm: &mut Vm, ty: &Type<'static>) -> Value {
    let Type::Record(_) = ty else {
        panic!("record allocation requires record type, got {ty}");
    };
    Value::from_ptr(vm.alloc(AllocType::Record, ty.layout()).as_ptr())
}

#[doc(hidden)]
pub fn record_field_ptr(base: Value, record_ty: &Type<'static>, name: &str) -> *mut u8 {
    let offset = record_ty
        .field_offset(name)
        .unwrap_or_else(|| panic!("record type {record_ty} has no field `{name}`"));
    unsafe { base.as_ptr::<u8>().add(offset) }
}

#[doc(hidden)]
pub fn record_field_ty<'a>(record_ty: &'a Type<'static>, name: &str) -> &'a Type<'static> {
    let Type::Record(fields) = record_ty else {
        panic!("field lookup requires record type, got {record_ty}");
    };
    &fields
        .as_slice()
        .iter()
        .find(|field| field.name == name)
        .unwrap_or_else(|| panic!("record type {record_ty} has no field `{name}`"))
        .ty
}

#[doc(hidden)]
pub unsafe fn decode_record_field<'vm, T: FromVm<'vm>>(
    vm: &'vm Vm,
    base: Value,
    record_ty: &Type<'static>,
    name: &str,
) -> T {
    let src = record_field_ptr(base, record_ty, name).cast_const();
    let field_ty = record_field_ty(record_ty, name);
    let value = match field_ty {
        Type::Record(_) => Value::from_ptr(src.cast_mut()),
        _ => unsafe { read_value(src) },
    };
    T::from_vm(vm, value)
}

#[doc(hidden)]
pub fn encode_record_field<T: IntoVm>(
    vm: &mut Vm,
    base: Value,
    record_ty: &Type<'static>,
    name: &str,
    value: T,
) {
    let dst = record_field_ptr(base, record_ty, name);
    let field_ty = record_field_ty(record_ty, name);
    let value = value.into_vm(vm);
    match field_ty {
        Type::Record(_) => unsafe { copy_record(value, dst, field_ty) },
        _ => write_value(dst, value),
    }
}

#[doc(hidden)]
pub unsafe fn copy_record(record: Value, dst: *mut u8, ty: &Type<'static>) {
    unsafe {
        std::ptr::copy_nonoverlapping(record.as_ptr::<u8>(), dst, ty.size());
    }
}

unsafe fn read_value(src: *const u8) -> Value {
    unsafe { src.cast::<Value>().read_unaligned() }
}

fn write_value(dst: *mut u8, value: Value) {
    unsafe { dst.cast::<Value>().write_unaligned(value) };
}

macro_rules! scalar_vm_type {
    ($ty:ty, $ptype:expr, $read:ident) => {
        impl PgType for $ty {
            const TYPE: Type<'static> = $ptype;
        }

        impl<'vm> FromVm<'vm> for $ty {
            fn from_vm(_: &'vm Vm, value: Value) -> Self {
                value.$read()
            }
        }

        impl IntoVm for $ty {
            fn into_vm(self, _: &mut Vm) -> Value {
                Value::from(self)
            }
        }
    };
}

impl PgType for &str {
    const TYPE: Type<'static> = Type::Str;
}

impl<T: PgType + ?Sized> PgType for &T {
    const TYPE: Type<'static> = T::TYPE;
}

impl<T: PgType + ?Sized> PgType for &mut T {
    const TYPE: Type<'static> = T::TYPE;
}

impl<'vm> FromVm<'vm> for &'vm str {
    fn from_vm(_: &'vm Vm, value: Value) -> Self {
        value.as_str()
    }
}

impl IntoVm for &str {
    fn into_vm(self, vm: &mut Vm) -> Value {
        vm.new_string(self.to_owned())
    }
}

impl PgType for String {
    const TYPE: Type<'static> = Type::Str;
}

impl<'vm> FromVm<'vm> for String {
    fn from_vm(_: &'vm Vm, value: Value) -> Self {
        value.as_str().to_owned()
    }
}

impl IntoVm for String {
    fn into_vm(self, vm: &mut Vm) -> Value {
        vm.new_string(self)
    }
}

scalar_vm_type!(i64, Type::Int, as_int);
scalar_vm_type!(f64, Type::Double, as_f64);
scalar_vm_type!(bool, Type::Bool, as_bool);

impl PgType for () {
    const TYPE: Type<'static> = Type::Void;
}

impl<'vm> FromVm<'vm> for () {
    fn from_vm(_: &'vm Vm, _: Value) -> Self {}
}

impl IntoVm for () {
    fn into_vm(self, _: &mut Vm) -> Value {
        Value::UNDEF
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::VmConfig;

    #[test]
    fn vm_conversion_traits_roundtrip_primitives() {
        let mut vm = Vm::new(VmConfig::default());
        let hello = vm.new_string("hello".to_owned());
        let world = vm.new_string("world".to_owned());
        *vm.r_mut(0) = hello;
        *vm.r_mut(1) = world;
        *vm.r_mut(2) = Value::from(42_i64);
        *vm.r_mut(3) = Value::from(3.5_f64);
        *vm.r_mut(4) = Value::from(true);

        let arg0 = <&str as FromVm>::from_vm(&vm, *vm.r(0));
        let arg1 = <&str as FromVm>::from_vm(&vm, *vm.r(1));
        assert_eq!((arg0, arg1), ("hello", "world"));
        assert_eq!(<i64 as FromVm>::from_vm(&vm, *vm.r(2)), 42);
        assert_eq!(<f64 as FromVm>::from_vm(&vm, *vm.r(3)), 3.5);
        assert!(<bool as FromVm>::from_vm(&vm, *vm.r(4)));
        assert_eq!(<String as FromVm>::from_vm(&vm, *vm.r(0)), "hello");

        let returned = "returned".into_vm(&mut vm);
        *vm.r_mut(0) = returned;
        assert_eq!(vm.r(0).as_str(), "returned");
        *vm.r_mut(0) = 7_i64.into_vm(&mut vm);
        assert_eq!(vm.r(0).as_int(), 7);
        *vm.r_mut(0) = 2.25_f64.into_vm(&mut vm);
        assert_eq!(vm.r(0).as_f64(), 2.25);
        *vm.r_mut(0) = false.into_vm(&mut vm);
        assert!(!vm.r(0).as_bool());
        assert_eq!(().into_vm(&mut vm), Value::UNDEF);
    }
}
